import Head from 'next/head'

import { trpc } from '@/lib/trpc'
import { cn } from '@/lib/utils'

export default function Home() {
  const hello = trpc.hello.useQuery({ text: 'client' })
  if (!hello.data) {
    return <div>Loading...</div>
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{hello.data.greeting}</main>
    </>
  )
}
