name: "Install"
description: "Sets up Node.js and runs install"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install pnpm
      shell: bash
      run: npm i -g pnpm

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Cache TypeScript TSBuild Info Files
      uses: actions/cache@v3
      with:
        path: "*/*/node_modules/.cache/tsbuildinfo.json"
        # Commit hash is for working around this: https://github.com/actions/cache/issues/106
        key: ${{ runner.os }}-cache-typescript-tsbuildinfo-${{ github.sha }}
        restore-keys: ${{ runner.os }}-cache-typescript-tsbuildinfo-

    - name: Install dependencies
      shell: bash
      run: pnpm install
