name: Run migrations
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Apply all pending migrations to the database
        run: bun drizzle:migration:run
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
